eureka:
    client:
        serviceUrl:
            defaultZone: http://kotlin-eureka:8761/eureka/
log:
    path: ./logs

spring:
    datasource:
        url: jdbc:mysql://mysql:3306/cannon?characterEncoding=utf8&useSSL=false
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
    profiles:
        active: local


