hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  eureka:
    enabled: true
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream
security:
  basic:
    enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 10MB
  aop:
    proxy-target-class: true
  redis:
    host: redis


server:
  tomcat:
    max-threads: 500
    min-spare-threads: 20
    uri-encoding: UTF-8
