log:
    path: /mnt/data/logs
spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false


eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/